@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.packingtape.tape;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;